### ISSUE TITLE
nim v2 is released but nimble file still restrict to `< 2.0.0`

### ISSUE THREAD

**Issue by bung87** [codex-storage/asynctest#6]
also after `compiler` package rename to `nim`, specify nim version in nimble file may not work as before, it will try to install the compiler code.

another problem is `testmodules` include in repository which seems not good, as they are frozen version, new nimble have task related dependencies, but it's a break change, since old nimble will give a parse error for this new syntax. so there's one step left to do, by specify `skipDirs = @["testmodules"]`, avoiding it install to nimble directory, but it still downloaded.

Thanks for reading! appreciate your efforts on this project.

**Comment by markspanbroek** [comment]
Thanks for reporting! #7 should fix this.
